general:
  debug_level: DEBUG

  # paths
  input_filelist_path: "/eos/user/k/kebarend/tWZ/FastFrames/input/filelist.txt"
  input_sumweights_path: "/eos/user/k/kebarend/tWZ/FastFrames/input/sum_of_weights.txt"
  output_path_histograms: "/eos/user/k/kebarend/tWZ/FastFrames/output_histograms/"
  output_path_ntuples: "/eos/user/k/kebarend/tWZ/ntuples/FastFrames/Preselection/${region}"

  # weights
  default_sumweights: "NOSYS"
  default_event_weights: "weight_mc_NOSYS"

  default_reco_tree_name: "reco"

  # path to the file with cross-sections
  xsection_files:
    - files: ["/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/dev/PMGTools/PMGxsecDB_mc16.txt"]
      campaigns: ["mc20a", "mc20d", "mc20e"]

  # name of the custom class
  custom_frame_name: "tWZClass"

  # automatic systematics?
  automatic_systematics: True
  nominal_only: False

  number_of_cpus: 4

  luminosity:
    mc20a: 36646.7
    mc20d: 44630.6
    mc20e: 58791.6


# define regions
regions:
  - name: "Preselection"
    selection: > 
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1

  - name: "LooseLeptons"
    selection: > 
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1
      && (nLooseElectrons_NOSYS + nLooseMuons_NOSYS) == 4

  - name: "TightLeptons"
    selection: > 
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1
      && (nLooseElectrons_NOSYS + nLooseMuons_NOSYS) == 4
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 4

  - name: "LeptonPt"
    selection: > 
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1
      && (nLooseElectrons_NOSYS + nLooseMuons_NOSYS) == 4
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 4
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10. && lep3_pt_NOSYS > 10.

  - name: "LeptonCharge"
    selection: > 
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1
      && (nLooseElectrons_NOSYS + nLooseMuons_NOSYS) == 4
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 4
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10. && lep3_pt_NOSYS > 10.
      && lep_sum_charge_NOSYS == 0

  - name: "OSSF"
    selection: > 
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1
      && (nLooseElectrons_NOSYS + nLooseMuons_NOSYS) == 4
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 4
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10. && lep3_pt_NOSYS > 10.
      && lep_sum_charge_NOSYS == 0
      && ossfFlag_NOSYS == 1

  - name: "ZCandidates"
    selection: > 
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1
      && (nLooseElectrons_NOSYS + nLooseMuons_NOSYS) == 4
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 4
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10. && lep3_pt_NOSYS > 10.
      && lep_sum_charge_NOSYS == 0
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 1 && nZCandidates_NOSYS == 1

  - name: "Jets"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1
      && (nLooseElectrons_NOSYS + nLooseMuons_NOSYS) == 4
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 4
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10. && lep3_pt_NOSYS > 10.
      && lep_sum_charge_NOSYS == 0
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 1 && nZCandidates_NOSYS == 1
      && nJets_NOSYS >= 2

  - name: "Bjets"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS
      && nJets_NOSYS >= 1
      && (nLooseElectrons_NOSYS + nLooseMuons_NOSYS) == 4
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 4
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10. && lep3_pt_NOSYS > 10.
      && lep_sum_charge_NOSYS == 0
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 1 && nZCandidates_NOSYS == 1
      && nJets_NOSYS >= 2
      && nBjets_NOSYS == 2

# define samples
samples:
  - name: "Data"
    dsids: [0]
    campaigns: ["2015", "2016", "2017", "2018"]
    simulation_type: "data"
  - name: "tWZ_DR1"
    dsids: [525955]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fastsim"
  - name: "tWZ_DR2"
    dsids: [525956]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fastsim"
  - name: "ttZ_Sherpa"
    dsids: [700309]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttZ_aMCPy8EG"
    dsids: [504330,504334,504342]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ZZ_Sherpa"
    dsids: [700587, 700600]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "WZ_Sherpa"
    dsids: [700588, 700601]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "VVV_Sherpa"
    dsids: [364242, 364243, 364244, 364245, 364246, 364247, 364248, 364249]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "tZq_aMCPy8EG"
    dsids: [512059]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fastsim"
  - name: "tt_PhPy8EG"
    dsids: [410472]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttW_Sherpa"
    dsids: [700205, 700168]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttGamma_MadPy8EG"
    dsids: [504554]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttH_PhPy8EG"
    dsids: [346345]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttWW_MadPy8EG"
    dsids: [410081]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttt_MGPy8EG"
    dsids: [304014]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "tttt_aMCPy8EG"
    dsids: [412043]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fastsim"
  - name: "VH_PhPy8EG_ZH"
    dsids: [346310, 364311, 364312]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "tW_PhPy8EG"
    dsids: [410648, 410649]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ZGamma_Sherpa"
    dsids: [700398, 700399, 700400]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"

ntuples:
  regions: ["${region}"]