general:
  debug_level: DEBUG

  # paths
  input_filelist_path: "/eos/user/k/kebarend/tWZ/FastFrames/input/filelist.txt"
  input_sumweights_path: "/eos/user/k/kebarend/tWZ/FastFrames/input/sum_of_weights.txt"
  output_path_histograms: "/eos/user/k/kebarend/tWZ/FastFrames/output_histograms/"
  output_path_ntuples: "/eos/user/k/kebarend/tWZ/ntuples/FastFrames/FinalSelection/ThreeLeptonChannel/${region}"

  # weights
  default_sumweights: "NOSYS"
  default_event_weights: "weight_mc_NOSYS"

  default_reco_tree_name: "reco"

  # path to the file with cross-sections
  xsection_files:
    - files: ["/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/dev/PMGTools/PMGxsecDB_mc16.txt"]
      campaigns: ["mc20a", "mc20d", "mc20e"]

  # name of the custom class
  custom_frame_name: "tWZClass"

  # automatic systematics?
  automatic_systematics: True
  nominal_only: False

  number_of_cpus: 6

  luminosity:
    mc20a: 36646.7
    mc20d: 44630.6
    mc20e: 58791.6

# # Embed ML model
# simple_onnx_inference:
#   - name: "NN"
#     model_paths: [
#       "/eos/user/k/kebarend/tWZ_analysis/outputs/NN_test.onnx"
#     ]
#     inputs:
#       "dense_input": [
#         "lep0_pt_NOSYS",
#         "lep0_eta_NOSYS",
#         "lep0_phi_NOSYS",
#         "lep1_pt_NOSYS",
#         "lep1_eta_NOSYS",
#         "lep1_phi_NOSYS",
#         "lep2_pt_NOSYS",
#         "lep2_eta_NOSYS",
#         "lep2_phi_NOSYS",
#         "lep3_pt_NOSYS",
#         "lep3_eta_NOSYS",
#         "lep3_phi_NOSYS",
#         "llll_mass_NOSYS",
#         "llll_pt_NOSYS",
#         "llll_eta_NOSYS",
#         "llll_phi_NOSYS",
#         "bjet0_pt_NOSYS",
#         "bjet0_eta_NOSYS",
#         "bjet0_phi_NOSYS",
#         "ZCandidate0_pt_NOSYS",
#         "ZCandidate0_mass_NOSYS",
#         "ZCandidate0_phi_NOSYS",
#         "ZCandidate0_eta_NOSYS",
#         "met_met_GeV_NOSYS",
#         "sumZCandidatePt_NOSYS",
#         "sumBjetPt_NOSYS",
#         "HT_NOSYS",
#         "LT_NOSYS",
#         "ST_NOSYS",
#         "SMT_NOSYS",
#         "nJets_NOSYS",
#         "nBjets_NOSYS"
#       ]
#     outputs:
#       "dense_2": ["NN_NOSYS"]


# define regions
regions:
  - name: "tWZSR"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS && 
      ((eee_NOSYS == 1 && el_triggers_NOSYS == 1 && mu_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 0 && nLooseElectrons_NOSYS == 3 && nTightElectrons_NOSYS >= 2 && nMediumMuons_NOSYS == 0)
      || (eemu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 2 && nTightElectrons_NOSYS >= 1 && nMediumMuons_NOSYS == 1 && nTightMuons_NOSYS >= 0)
      || (emumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 1 && nTightElectrons_NOSYS >= 0 && nMediumMuons_NOSYS == 2 && nTightMuons_NOSYS >= 1)
      || (mumumu_NOSYS == 1 && el_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 0 && mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1 && nLooseElectrons_NOSYS == 0 && nMediumMuons_NOSYS == 3 && nTightMuons_NOSYS >= 2))
      && (nLooseElectrons_NOSYS + nMediumMuons_NOSYS) == 3
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 3
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10.
      && nOSSF_NOSYS >= 1
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 1 && nZCandidates_NOSYS == 1
      && nJets_NOSYS >= 2
      && nBjets_NOSYS == 1
      && met_met_GeV_NOSYS > 30.

  - name: "ttZCR"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS && 
      ((eee_NOSYS == 1 && el_triggers_NOSYS == 1 && mu_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 0 && nLooseElectrons_NOSYS == 3 && nTightElectrons_NOSYS >= 2 && nMediumMuons_NOSYS == 0)
      || (eemu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 2 && nTightElectrons_NOSYS >= 1 && nMediumMuons_NOSYS == 1 && nTightMuons_NOSYS >= 0)
      || (emumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 1 && nTightElectrons_NOSYS >= 0 && nMediumMuons_NOSYS == 2 && nTightMuons_NOSYS >= 1)
      || (mumumu_NOSYS == 1 && el_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 0 && mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1 && nLooseElectrons_NOSYS == 0 && nMediumMuons_NOSYS == 3 && nTightMuons_NOSYS >= 2))
      && (nLooseElectrons_NOSYS + nMediumMuons_NOSYS) == 3
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 3
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10.
      && nOSSF_NOSYS >= 1
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 1 && nZCandidates_NOSYS == 1
      && nJets_NOSYS >= 2
      && nBjets_NOSYS >= 2

  - name: "WZCR"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS && 
      ((eee_NOSYS == 1 && el_triggers_NOSYS == 1 && mu_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 0 && nLooseElectrons_NOSYS == 3 && nTightElectrons_NOSYS >= 2 && nMediumMuons_NOSYS == 0)
      || (eemu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 2 && nTightElectrons_NOSYS >= 1 && nMediumMuons_NOSYS == 1 && nTightMuons_NOSYS >= 0)
      || (emumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 1 && nTightElectrons_NOSYS >= 0 && nMediumMuons_NOSYS == 2 && nTightMuons_NOSYS >= 1)
      || (mumumu_NOSYS == 1 && el_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 0 && mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1 && nLooseElectrons_NOSYS == 0 && nMediumMuons_NOSYS == 3 && nTightMuons_NOSYS >= 2))
      && (nLooseElectrons_NOSYS + nMediumMuons_NOSYS) == 3
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 3
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10.
      && nOSSF_NOSYS >= 1
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 1 && nZCandidates_NOSYS == 1
      && nJets_NOSYS == 2
      && nBjets_NOSYS == 0
      && met_met_GeV_NOSYS > 30.

  - name: "ZZCR"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS && 
      ((eeee_NOSYS == 1 && el_triggers_NOSYS == 1 && mu_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 0 && nLooseElectrons_NOSYS == 4 && nTightElectrons_NOSYS >= 3 && nMediumMuons_NOSYS == 0)
      || (eeemu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 3 && nTightElectrons_NOSYS >= 2 && nMediumMuons_NOSYS == 1 && nTightMuons_NOSYS >= 0)
      || (eemumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 2 && nTightElectrons_NOSYS >= 1 && nMediumMuons_NOSYS == 2 && nTightMuons_NOSYS >= 1)
      || (emumumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 1 && nTightElectrons_NOSYS >= 0 && nMediumMuons_NOSYS == 3 && nTightMuons_NOSYS >= 2)
      || (mumumumu_NOSYS == 1 && el_triggers_NOSYS == 0 && mu_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 0 && mu_firedTriggers_NOSYS == 1 && nLooseElectrons_NOSYS == 0 && nMediumMuons_NOSYS == 4 && nTightMuons_NOSYS >= 3))
      && (nLooseElectrons_NOSYS + nMediumMuons_NOSYS) == 4
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 4
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10. && lep3_pt_NOSYS > 10.
      && nOSSF_NOSYS >= 2
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 2 && nZCandidates_NOSYS == 2
      && nJets_NOSYS >= 2
  
  - name: "ttCR"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS && 
      ((eee_NOSYS == 1 && el_triggers_NOSYS == 1 && mu_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 0 && nLooseElectrons_NOSYS == 3 && nTightElectrons_NOSYS >= 2 && nMediumMuons_NOSYS == 0)
      || (eemu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 2 && nTightElectrons_NOSYS >= 1 && nMediumMuons_NOSYS == 1 && nTightMuons_NOSYS >= 0)
      || (emumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 1 && nTightElectrons_NOSYS >= 0 && nMediumMuons_NOSYS == 2 && nTightMuons_NOSYS >= 1)
      || (mumumu_NOSYS == 1 && el_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 0 && mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1 && nLooseElectrons_NOSYS == 0 && nMediumMuons_NOSYS == 3 && nTightMuons_NOSYS >= 2))
      && (nLooseElectrons_NOSYS + nMediumMuons_NOSYS) == 3
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 3
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10.
      && abs(lep_sum_charge_NOSYS) == 1
      && nOSSF_NOSYS == 0
      && nJets_NOSYS >= 2
      && nBjets_NOSYS == 1

  - name: "DYCR"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS && 
      ((eee_NOSYS == 1 && el_triggers_NOSYS == 1 && mu_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 0 && nLooseElectrons_NOSYS == 3 && nTightElectrons_NOSYS >= 2 && nMediumMuons_NOSYS == 0)
      || (eemu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 2 && nTightElectrons_NOSYS >= 1 && nMediumMuons_NOSYS == 1 && nTightMuons_NOSYS >= 0)
      || (emumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 1 && nTightElectrons_NOSYS >= 0 && nMediumMuons_NOSYS == 2 && nTightMuons_NOSYS >= 1)
      || (mumumu_NOSYS == 1 && el_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 0 && mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1 && nLooseElectrons_NOSYS == 0 && nMediumMuons_NOSYS == 3 && nTightMuons_NOSYS >= 2))
      && (nLooseElectrons_NOSYS + nMediumMuons_NOSYS) == 3
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 3
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10.
      && abs(lep_sum_charge_NOSYS) == 1
      && nOSSF_NOSYS >= 1
      && nJets_NOSYS >= 2
      && nBjets_NOSYS == 0
      && met_met_GeV_NOSYS < 30.

  - name: "VR1"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS && 
      ((eee_NOSYS == 1 && el_triggers_NOSYS == 1 && mu_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 0 && nLooseElectrons_NOSYS == 3 && nTightElectrons_NOSYS >= 2 && nMediumMuons_NOSYS == 0)
      || (eemu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 2 && nTightElectrons_NOSYS >= 1 && nMediumMuons_NOSYS == 1 && nTightMuons_NOSYS >= 0)
      || (emumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 1 && nTightElectrons_NOSYS >= 0 && nMediumMuons_NOSYS == 2 && nTightMuons_NOSYS >= 1)
      || (mumumu_NOSYS == 1 && el_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 0 && mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1 && nLooseElectrons_NOSYS == 0 && nMediumMuons_NOSYS == 3 && nTightMuons_NOSYS >= 2))
      && (nLooseElectrons_NOSYS + nMediumMuons_NOSYS) == 3
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 3
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10.
      && nOSSF_NOSYS >= 1
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 1 && nZCandidates_NOSYS == 1
      && nJets_NOSYS >= 2
      && nBjets_NOSYS == 1
      && met_met_GeV_NOSYS < 30.

  - name: "VR2"
    selection: >
      passedElectronPtEtaCut_NOSYS && passedMuonPtEtaCut_NOSYS && 
      ((eee_NOSYS == 1 && el_triggers_NOSYS == 1 && mu_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 0 && nLooseElectrons_NOSYS == 3 && nTightElectrons_NOSYS >= 2 && nMediumMuons_NOSYS == 0)
      || (eemu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 2 && nTightElectrons_NOSYS >= 1 && nMediumMuons_NOSYS == 1 && nTightMuons_NOSYS >= 0)
      || (emumu_NOSYS == 1 && ((el_triggers_NOSYS == 1 && el_firedTriggers_NOSYS == 1) || (mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1)) && nLooseElectrons_NOSYS == 1 && nTightElectrons_NOSYS >= 0 && nMediumMuons_NOSYS == 2 && nTightMuons_NOSYS >= 1)
      || (mumumu_NOSYS == 1 && el_triggers_NOSYS == 0 && el_firedTriggers_NOSYS == 0 && mu_triggers_NOSYS == 1 && mu_firedTriggers_NOSYS == 1 && nLooseElectrons_NOSYS == 0 && nMediumMuons_NOSYS == 3 && nTightMuons_NOSYS >= 2))
      && (nLooseElectrons_NOSYS + nMediumMuons_NOSYS) == 3
      && (nTightElectrons_NOSYS + nTightMuons_NOSYS) == 3
      && lep0_pt_NOSYS > 28. && lep1_pt_NOSYS > 18. && lep2_pt_NOSYS > 10.
      && nOSSF_NOSYS >= 1
      && ossfFlag_NOSYS == 1
      && nOSSF_inZWindow_NOSYS == 0 && nZCandidates_NOSYS == 0
      && nJets_NOSYS >= 2
      && nBjets_NOSYS == 1
      && met_met_GeV_NOSYS > 30.

# define samples
samples:
  - name: "Data"
    dsids: [0]
    campaigns: ["2015", "2016", "2017", "2018"]
    simulation_type: "data"
  - name: "tWZ_DR1"
    dsids: [525955]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fastsim"
  - name: "tWZ_DR2"
    dsids: [525956]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fastsim"
  - name: "ttZ_Sherpa"
    dsids: [700309]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttZ_aMCPy8EG"
    dsids: [504330,504334,504342]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ZZ_Sherpa"
    dsids: [700587, 700600]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "WZ_Sherpa"
    dsids: [700588, 700601]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "VVV_Sherpa"
    dsids: [364242, 364243, 364244, 364245, 364246, 364247, 364248, 364249]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "tZq_aMCPy8EG"
    dsids: [512059]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fastsim"
  - name: "tt_PhPy8EG"
    dsids: [410472]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttW_Sherpa"
    dsids: [700205, 700168]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttGamma_MadPy8EG"
    dsids: [504554]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttH_PhPy8EG"
    dsids: [346345]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttWW_MadPy8EG"
    dsids: [410081]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ttt_MGPy8EG"
    dsids: [304014]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "tttt_aMCPy8EG"
    dsids: [412043]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fastsim"
  - name: "VH_PhPy8EG"
    dsids: [346310, 346311, 346312]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "tW_PhPy8EG"
    dsids: [410648, 410649]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"
  - name: "ZGamma_Sherpa"
    dsids: [700398, 700399, 700400]
    campaigns: ["mc20a", "mc20d", "mc20e"]
    simulation_type: "fullsim"

ntuples:
  regions: ["${region}"]